version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-raul
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
