version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-raul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/raul.test.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/raul.test.crt:/etc/ssl/certs/raul.test.crt:ro
      - ./certs/raul.test.key:/etc/ssl/private/raul.test.key:ro
      - ./html:/usr/share/nginx/html
      - ./conf/htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped